apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ae3q0sg49-java-quarkus
  janus-idp.io/tekton: ae3q0sg49-java-quarkus
  backstage.io/kubernetes-id: ae3q0sg49-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ae3q0sg49-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
